name: Run PHP CodeSniffer

# Run PHPCBF to fix changes then annotate PHPCS
# NB: Pull requests from forks do not have access to repository secrets so cannot commit changes.

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  php-codesniffer:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.4' ]

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Install PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
        with:
          php-version: ${{ matrix.php }}
          tools: composer, cs2pr
          extensions: zip

      - name: Run composer install
        run: composer install

      - name: Run PHPCBF to fix what it can
        continue-on-error: true
        run: vendor/bin/phpcbf

      - name: Run PHPCS to add annotations to all the code
        continue-on-error: true
        run: vendor/bin/phpcs -q -n --report=checkstyle | cs2pr

      - name: Fail if there are still phpcs errors in the production code
        id: run-phpcs
        run: vendor/bin/phpcs includes templates
        continue-on-error: true # Continue so we can commit the badge.

      - name: Check success
        if: ${{ github.event_name != 'pull_request' && steps.run-phpcs.outcome == 'success' }}
        run: curl -o .github/phpcs.svg https://img.shields.io/badge/PHPCS-WordPress%20Coding%20Standards-8892BF.svg

      - name: Check failures
        if: ${{ github.event_name != 'pull_request' && steps.run-phpcs.outcome != 'success' }}
        run: curl -o .github/phpcs.svg https://img.shields.io/badge/PHPCS-WordPress%20Coding%20Standards%20❌-lightgrey.svg

      - name: Commit PHPCBF changes
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "🤖 PHPCBF"

      - name: Did we fail?
        if: ${{ steps.run-phpcs.outcome != 'success' }}
        run: exit 1

